#define FBO_BG_A 0xFFEBEBEB
#define FBO_BG_B 0xFFCCCCCC
static unsigned long fb_bg_text_data[16][16] = 
{
	{
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A,
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B
	},
	{
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A,
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B
	},
	{
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A,
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B
	},
	{
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A,
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B
	},
	{
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A,
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B
	},
	{
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A,
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B
	},
	{
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A,
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B
	},
	{
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A,
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B
	},

	{
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B,
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A
	},

	{
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B,
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A
	},
	{
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B,
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A
	},
	{
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B,
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A
	},
	{
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B,
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A
	},
	{
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B,
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A
	},
	{
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B,
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A
	},
	{
		FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B, FBO_BG_B,
		FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A, FBO_BG_A
	},
};